server_port: 8080

reconciler:
  resources_poller:
    interval: 10 min

kubernetes:
  namespace: default
  kubeconfig: config/kubeconfig

crd:
  files:
    - config/crd-list/provisioningrequests.o2ims.provisioning.oran.org.json
  load: true

# Possible values for DataStore are:
#   - k8s (Kubernetes)
#   - json (JSON file)
#   - opensearch (OpenSearch)//TODO

# Possible values for BackendType are:
#   - omc_rest_v1 (OMC REST API)
#   - omc_rest_simulator (OMC REST API Simulator)

# Example:
#   data_store: k8s
#   backend_type: omc_rest_v1
#   omc:
#     url: "https://gui-omc.cniscrlab-cl10.deac.gic.ericsson.se/"
#     username: "admin"
#     password: "admin"

data_store: k8s
backend_type: omc_rest_v1
omc:
  url: "https://gui-omc.cniscrlab-cl10.deac.gic.ericsson.se/"
  username: "apiadmin"
  password: "Ericsson@123"
