apiVersion: o2ims.provisioning.oran.org/v1alpha1
kind: ProvisioningRequest
metadata:
  name: crdi-2
spec:
  description: Test provisioning request
  name: Test Cluster Provisioning
  templateName: cluster-template
  templateParameters:
    cluster_name: test-cluster
    node_count: 3
    node_type: worker
  templateVersion: v1.1

