templateParameters:
  clusterParams:
    ccd_env:
      apiserverfqdn: api.crlab-vdu014-cnis.deac.gic.ericsson.se
    params:
      alertmanager_hostname: alert-manager.crlab-vdu014-cnis.deac.gic.ericsson.se
      apiserver_extra_sans:
      - api.crlab-vdu014-cnis.deac.gic.ericsson.se
      - api.eccd.local
      bootstrap_node_ip: 10.87.87.84
      control_plane_external_ip: 10.87.87.84
      cr-registry_hostname: registry.crlab-vdu014-cnis.deac.gic.ericsson.se
      ecfe:
        address-pools:
        - addresses:
          - 10.87.87.162-10.87.87.162
          name: edge-ecfe-om-pool
        - addresses:
          - 10.33.17.148-10.33.17.151
          name: ran-om-pool
        static-bfd-peers:
        - peer-address: 10.87.87.81
        - peer-address: 10.33.17.57
      ingress_ip: 10.87.87.162
      mcm_fqdn: 10.87.87.137
      nameservers:
      - 164.48.10.101
      - 164.48.10.102
      nels_customer_id: 800141
      nels_host_ip: 100.73.25.194
      nels_host_name: ns4p.nelsaas.svc.gic.ericsson.se
      nels_port: 9099
      nels_swlt_id: STB-CCD-1
      networks:
      - name: edgeccdintsp
        vlan: 3320
      - gateway_ipv4: 10.87.87.81
        ip_pools:
        - end: 10.87.87.84
          prefix: 29
          start: 10.87.87.84
        name: edgeccdomsp
        vlan: 1138
      - gateway_ipv4: 10.33.17.57
        ip_pools:
        - end: 10.33.17.58
          prefix: 29
          start: 10.33.17.58
        name: edgeranoamsp
        vlan: 1111
      ntp_servers:
      - 164.48.10.70
      - 164.48.10.90
      omc_fqdn: gui-omc.cniscrlab-cl10.deac.gic.ericsson.se
      remote_image_server_url: https://10.87.87.137:6182
      routes:
        config:
        - next-hop-address:
            gateway-from-net:
              net-name: edgeccdomsp
          next-hop-interface: edge_ccd_om
      sftp_url: ftps://10.87.87.137:22
      timezone: UTC
      value_packs:
      - value_packs/CXP9043234-2.31.0-6070d2dc4168e9763cd57d05caaf09e5.tar.gz
      victoria_metrics_hostname: prometheus.crlab-vdu014-cnis.deac.gic.ericsson.se
    user_secrets:
      bmc_password:
        files:
        - secrets/bmc_password
        path: cmc-secret/computes/dl110-002/bmc_password
        type: file
      bmc_username:
        files:
        - secrets/bmc_username
        path: cmc-secret/computes/dl110-002/bmc_username
        type: file
  resourceParams:
    managed_element:
      product: CNIS
      software_version: '1.15'
      type: single-server
    single-server-configuration:
      cluster:
        ccd_config:
          cluster_template_name: cnis1.15_dl110_vdu_midband
          name: dl110-02-ccds
          software_version: 2.31.0
      equipment:
        compute:
          server_profile_name: cnis1.15_dl110_vdu_fw_bios.yaml
          service_id: dl110-002-ilo
          user_label: dl110-02
        relay:
          relay_configuration:
            address_ranges:
            - address_from: 10.87.87.218
              address_range_ipv4_id: DL110-002-ilo
              address_to: 10.87.87.218
              binding_id: dl110-002-ilo
              user_label: DL110-002-ilo
            location_info: Remote DRAN Site Aachen - DL110-002
            next_hop_address_ipv4: 10.87.87.209
            ntp_servers:
            - 164.48.10.70
            - 164.48.10.90
            postal_address:
              house_number: 20
              postal_code: 97231
              room: Hall E
            prefix_length_ipv4: 28
            relay_address_ipv4: 10.87.87.209
            user_label: DL110-002
          relay_id: Aachen-dl110-02
        sdi_name: cniscrlab-rem
        v_pod:
          vpod_id: edge-vpod-dl110-02
